#!/usr/bin/sh

#
# The shell script will make a set of VGA demo bit files
# for various VGA resolutions and fonts.
#

makeone()
{
	echo "--------------------------------------------"
	echo "Building for VGA $1 - Two Color Mode = $2"
	make clean VGA_MODE=$1 TWO_COLOR_MODE=$2
	make all   VGA_MODE=$1 TWO_COLOR_MODE=$2
	echo "--------------------------------------------"
}

make500k()
{
	echo "--------------------------------------------"
	echo "Building for VGA $1 - Two Color Mode = $2"
	echo "(for the Papilio One 500k Board)"
	make clean VGA_MODE=$1 TWO_COLOR_MODE=$2 PART=xc3s500e-4-vq100 PLATFORM=Papilio_One
	make all   VGA_MODE=$1 TWO_COLOR_MODE=$2 PART=xc3s500e-4-vq100 PLATFORM=Papilio_One
	echo "--------------------------------------------"
}

# Make one for the Papilio One 500K Board
make500k 1024x768_128x64x256  FALSE

# The rest are for the Papilio Plus Board (with a LX9 device)
makeone 640x480_80x40x256    FALSE
makeone 800x600_100x50x256   FALSE
makeone 1024x768_128x64x256  FALSE
makeone 1152x864_144x72x256  FALSE

makeone 640x480_80x30x128    FALSE
makeone 1024x768_128x48x128  FALSE
makeone 1152x864_144x54x128  FALSE
makeone 1280x1024_160x64x128 TRUE
makeone 1600x1200_200x75x128 TRUE

ls -l *.bit
